version: '3'

volumes:
  dbdata6:

services:
  mongodb:
    image: mongo:latest
    env_file: .env
    volumes:
      - dbdata6:/data/db
      - ./sampleDB/.:/app/dump/
      - ./mongorestore.sh:/docker-entrypoint-initdb.d/mongorestore.sh
    ports:
      - '27017:27017'
  
  telegram_bot:
    build: ./
    env_file: .env
    depends_on:
      - mongodb
